table <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", nrows = 2880, skip = 66636, stringsAsFactors = FALSE)
table2 <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", nrows = 5, stringsAsFactors = FALSE)
names(table) <- names(table2)
table <- cbind("Date_Time" = strptime(paste(table[,1],table[,2]), "%d/%m/%Y %H:%M:%S"),table)

png(filename = "plot1.png", width = 480, height = 480)
plot(table$Sub_metering_1 ~ table$Date_Time, type = "n", xlab = "", ylab = "Energy Sub metering" )
lines(table$Date_Time, table$Sub_metering_1, col = "black")
lines(table$Date_Time, table$Sub_metering_2, col = "red")
lines(table$Date_Time, table$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = 1)
dev.off()